config/routes.rb
Rails.application.routes.draw do
  root "cocktails#index"
   resources :cocktails do
     resources :doses, only: [ :new, :create ]
     resources :reviews, only: [ :create ]
   end
   resources :doses, only: :destroy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
  has_many :reviews, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    @review = Review.new

  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(strong_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end


  private
    def strong_params
    params.require(:cocktail).permit(:name, :photo)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(strong_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail_id)
  end

  private

  def strong_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
     else
       render 'new'
    end
  end

  private
  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to cocktails_path, class: "navig-link" do %>
  <h5>Barra de Cócteles</h5>
  <% end %>
   <%= link_to "Create a new cocktail", "/cocktails/new", class: "home-button btn btn-primary" %>
</div>



<div class="banner">
  <div class="banner-content">
    <h1>Barra de Cócteles</h1>
    <p>Best cocktails in town</p>
  </div>
</div>

<div class="container">
<h1 class='cocktail-header text-center mb-4'>Check out the classics</h1>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-12 col-md-6 col-lg-3">
        <%= link_to cocktail_path(cocktail), class: "card-link" do %>
        <div class="card" style="background: linear-gradient(rgba(0,10,10,0.2) 0%, rgba(10,10,10,0.2) 0%), url(
        '<%= cl_image_path cocktail.photo.key, height: 300, width: 200, crop: :fill if
        cocktail.photo.attached?%>');">
          <div class="cocktail-card-content">
            <h2><%= cocktail.name %></h2>
          </div>
        </div>
        <br>
       <% end %>
      </div>
    <% end  %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-static-top">
  <%= link_to cocktails_path, class: "navig-link" do %>
  <h5>Barra de Cócteles</h5>
  <% end %>
  <%= link_to "Back to all cocktails", cocktails_path, class: "btn btn-primary" %>
</div>

  <div class="container">
    <h1 class="page-title text-center">Create a new cocktail</h1>
    <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: "form-button btn btn-primary"%>
    <% end %>
  </div>


 <%= video_tag "background.mp4", autoplay: :autoplay, loop: :loop, muted: :muted, class: "bg-video" %>

app/views/cocktails/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-static-top">
  <%= link_to cocktails_path, class: "navig-link" do %>
  <h5>Barra de Cócteles</h5>
  <% end %>
  <%= link_to "Back to all cocktails", cocktails_path, class: "btn btn-primary" %>
</div>

<div class="flexbox">
    <div class="row-show">
      <div class="col-sm-12 col-md-6">
        <h1 class="cocktail-name"><%=  @cocktail.name %></h1>
        <h5 class="recipe-headline">Recipe</h5>
        <% @cocktail.doses.each do |dose| %>
           <div class="ingredient-content d-inline">
             <div class="dose-name d-inline">
              <%= dose.ingredient.name %> | <%= dose.description %>
               <%= link_to dose_path(dose),
                  method: :delete,
                  data: { confirm: "Are you sure you want to delete?" } do %>
                  <i class="trash-icon far fa-trash-alt d-inline ml-2"></i>
               <% end  %>
             </div>
           </div>
        <% end  %>
        <div class="btn btn-primary mt-3">
        <%= link_to 'Add Ingredients', new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <div class="cocktail-photo mt-5 p-5">
      <%= cl_image_tag @cocktail.photo.key, width: 300, height: 450, crop: :fill, radius: 4, class: "mt-3" %>
    </div>
</div>

<div class="container">
  <div class="reviews-container d-flex flex-column m-3">
  <h3>Reviews</h3>
  <% if @cocktail.reviews.empty? %>
  <p>Be the first to leave a review</p>
  <% else %>
    <ul class="list-group d-flex">
      <% @cocktail.reviews.each do |review| %>
        <li class="list-group-item d-flex flex-row justify-center mt-1 py-3">
           <%= review.content %>
            <% review.rating.times do %>
               <i class="fas fa-star"></i>
            <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

  <div class='review-form-container justify-left'>
    <%= render "reviews/new", cocktail: @cocktail, review: @review %>
  </div>

</div>

app/views/doses/new.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-static-top">
  <%= link_to cocktails_path, class: "navig-link" do %>
  <h5>Barra de Cócteles</h5>
  <% end %>
  <%= link_to "Back to all cocktails", cocktails_path, class: "btn btn-primary" %>
</div>

  <div class="container mt-3">
    <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.association :ingredient, placeholder: 'select'%>
      <%= f.input :description %>
      <%= f.button :submit, class: "form-button btn btn-primary" %>
    <% end %>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_new.html.erb
  <div class='review-form-container' >
  <h4 class='header text-center mt-5'>Add a review</h4>
  <div class="review-container mt-3">
    <%= simple_form_for [cocktail, review] do |f| %>
      <%= f.input :rating, collection: 0..5 %>
      <%= f.input :content %>
      <%= f.button :submit, class: "form-button btn btn-primary" %>
    <% end %>

  </div>



  </div>